// Generated by CoffeeScript 1.6.3
(function() {
  require(['interact', 'debug'], function(interact, debug) {
    window.ui = {};
    window.ui.interact = interact;
    if (!window.iron) {
      window.iron = debug.iron;
    }
    return window.iron.ui = window.ui;
  });

}).call(this);
