// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return {
      iron: {
        interactAt: function(_arg) {
          var x, y;
          x = _arg[0], y = _arg[1];
          return ['test'];
        },
        screenPos: function(a) {
          return a;
        }
      }
    };
  });

}).call(this);
