// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var blit, clear, el, html, model, show;
    el = function() {
      return $('#interact');
    };
    blit = function(html) {
      return el().html(html);
    };
    clear = function() {
      return el().html('');
    };
    html = function(model) {
      if (model.actions.length > 0) {
        return blit(Handlebars.templates.interact(model));
      } else {
        return clear();
      }
    };
    model = function(x, y, actions) {
      return {
        x: x,
        y: y,
        actions: actions
      };
    };
    show = function(x, y) {
      var actions, pt, xt, yt, _ref;
      pt = [x, y];
      actions = iron.interactAt([x, y]);
      _ref = iron.screenPos([x * 32, y * 32]), xt = _ref[0], yt = _ref[1];
      return html(model(xt, yt, actions));
    };
    return {
      show: show
    };
  });

}).call(this);
